/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:df151002-1b1d-43c8-a3b5-cbcc49a4c221",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_fjalETH7H",
    "aws_user_pools_web_client_id": "6bh1e752uaknqnj47atro5v4v6",
    "oauth": {
        "domain": "julius01055aaa68-055aaa68-staging.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
